const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const getPeriod=()=>{const h=new Date().getHours();return h>=4&&h<10?'morning':h>=10&&h<20?'day':'night'};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentStage=Number(localStorage.getItem('ss-stage')??5);
let caught=new Set(JSON.parse(localStorage.getItem('ss-caught')||'[]'));
let excluded=new Set(JSON.parse(localStorage.getItem('ss-excluded')||'[]'));
let records=JSON.parse(localStorage.getItem('ss-records')||'{}');
let toastTimer=null;

const recommendations={
 'ヘラクロス':{score:5,label:'最有力',cls:'top',reason:'高い攻撃と格闘火力。アカネ以降の主要戦で長く活躍。'},
 'ケーシィ':{score:5,label:'最有力',cls:'top',reason:'ユンゲラー以降の特攻・素早さが非常に高く、特殊エース向き。'},
 'メリープ':{score:5,label:'最有力',cls:'top',reason:'デンリュウまで育てると安定した電気枠。耐久と特攻が扱いやすい。'},
 'イシツブテ':{score:4,label:'有力',cls:'good',reason:'序盤～中盤の相性が良く、物理耐久も高い。ゴローンでも十分実用的。'},
 'ゴース':{score:4,label:'有力',cls:'good',reason:'ゴースト枠兼特殊アタッカー。進化できるほど評価が上がる。'},
 'ズバット':{score:4,label:'有力',cls:'good',reason:'序盤は弱めだが、なつき進化のクロバットが高速で使いやすい。'},
 'ストライク':{score:4,label:'有力',cls:'good',reason:'高い攻撃・素早さで即戦力。むしとりたいかいで入手可能。'},
 'カイロス':{score:4,label:'有力',cls:'good',reason:'高い物理火力で旅の即戦力。進化なしで完成が早い。'},
 'ニドラン♀':{score:4,label:'有力',cls:'good',reason:'進化後の技範囲が広く、長期運用しやすい。'},
 'ニドラン♂':{score:4,label:'有力',cls:'good',reason:'進化後の技範囲が広く、長期運用しやすい。'},
 'ロコン':{score:4,label:'有力',cls:'good',reason:'ソウルシルバーの炎枠候補。特に炎タイプ不足なら価値が高い。'},
 'コイキング':{score:4,label:'有力',cls:'good',reason:'育成は必要だが、ギャラドス進化後は非常に強力。'},
 'メノクラゲ':{score:3,label:'候補',cls:'okay',reason:'水・毒の耐性と素早さが優秀。なみのり要員にもできる。'},
 'ウパー':{score:3,label:'候補',cls:'okay',reason:'水・地面で弱点が少なく、ストーリー攻略で扱いやすい。'},
 'スリープ':{score:3,label:'候補',cls:'okay',reason:'序盤のエスパー枠。耐久寄りで安定するが、ケーシィ系より火力は控えめ。'},
 'オニスズメ':{score:3,label:'候補',cls:'okay',reason:'序盤の飛行枠として即戦力。オニドリルまでの完成も早い。'},
 'クラブ':{score:3,label:'候補',cls:'okay',reason:'キングラーの物理攻撃は高い。水技と攻撃種別の噛み合わせには注意。'},
 'オドシシ':{score:3,label:'候補',cls:'okay',reason:'捕獲直後から能力がまとまり、進化なしで使える即戦力。'},
 'ポッポ':{score:3,label:'候補',cls:'okay',reason:'そらをとぶ要員として便利。終盤火力はやや控えめ。'},
 'オタチ':{score:3,label:'便利',cls:'utility',reason:'オオタチに進化後、フィールド技を多く担当できる便利枠。'},
 'タマタマ':{score:3,label:'候補',cls:'okay',reason:'進化後は高い特攻を持つ。進化アイテムと技習得時期を意識。'},
 'パラス':{score:2,label:'図鑑向け',cls:'dex',reason:'状態異常など個性はあるが、旅パ効率では優先度低め。'},
 'レディバ':{score:2,label:'図鑑向け',cls:'dex',reason:'サポート寄りで火力が低く、通常攻略では優先度低め。'}
};
const natures=['がんばりや','さみしがり','ゆうかん','いじっぱり','やんちゃ','ずぶとい','すなお','のんき','わんぱく','のうてんき','おくびょう','せっかち','まじめ','ようき','むじゃき','ひかえめ','おっとり','れいせい','てれや','うっかりや','おだやか','おとなしい','なまいき','しんちょう','きまぐれ'];

function notify(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1500)}
function uniqueSpecies(){return [...new Set(E.map(e=>e.name))]}
function save(){localStorage.setItem('ss-stage',currentStage);localStorage.setItem('ss-caught',JSON.stringify([...caught]));localStorage.setItem('ss-excluded',JSON.stringify([...excluded]));localStorage.setItem('ss-records',JSON.stringify(records));}
function expOf(e){const b=(meta[e.name]||[null,null])[1];if(!b)return null;return Math.floor(b*((e.min+e.max)/2)/7)}
function catchRate(name){return (meta[name]||[null])[0]}
function timeOK(e,p){return e.time==='all'||e.time===p}
function recOf(name){return recommendations[name]||null}
function recBadge(name){const r=recOf(name);return r?`<span class="rec rec-${r.cls}">${r.label}</span>`:''}
function avgLevel(e){return (e.min+e.max)/2}
function levelText(e){return e.min===e.max?`Lv${e.min}`:`Lv${e.min}–${e.max}`}
function dedupeBest(arr){const m=new Map();for(const e of arr){const old=m.get(e.name);if(!old||e.rate>old.rate||(e.rate===old.rate&&avgLevel(e)>avgLevel(old)))m.set(e.name,e)}return [...m.values()]}
function recordFor(name){const src=records[name]||{};let currentState=src.currentState||'';let plan=src.plan||'';if(!currentState&&src.status==='手持ち')currentState='手持ち';if(!currentState&&src.status==='ボックス')currentState='ボックス';if(!plan&&['育成中','育成予定','進化待ち','交換予定','図鑑用','保留','特になし'].includes(src.status))plan=src.status;return {...src,currentState,plan};}
function recordSummary(name){const r=recordFor(name),parts=[];if(r.level)parts.push(`Lv${r.level}`);if(r.currentState)parts.push(r.currentState);if(r.plan)parts.push(r.plan);return parts.join(' ・ ')}
function expGrade(e){const ex=e.exp||expOf(e)||0,rate=e.rate||0;if((rate>=40&&ex>=130)||(rate>=20&&ex>=180))return{level:4,label:'◎ 高効率',cls:'best',note:'経験値と出現率の両方が優秀'};if((rate>=20&&ex>=130)||(rate>=10&&ex>=180)||(rate>=40&&ex>=100))return{level:3,label:'○ おすすめ',cls:'good',note:'安定して経験値を稼ぎやすい'};if(ex>=180&&rate<10)return{level:2,label:'△ 高EXP・低出現',cls:'mid',note:'1匹は大きいが、出会いにくい'};if(ex>=120||rate>=20)return{level:2,label:'△ 条件付き',cls:'mid',note:'条件次第では使える'};return{level:1,label:'— 低め',cls:'low',note:'経験値目的では優先度低め'};}
function expInternalScore(e){const g=expGrade(e);return g.level*100000+(e.exp||0)*100+Math.min(e.rate||0,99)}
function targetPriority(e){return (recOf(e.name)?.score||0)*10000+Math.min(e.rate,60)*100+avgLevel(e)}

function actionButtons(name,{large=false}={}){const isCaught=caught.has(name),isExcluded=excluded.has(name);return `<div class="${large?'decision-actions':'encounter-actions'}"><button class="action-btn primary" data-catch="${name}">${isCaught?'✓ 捕獲済み':'捕獲済みにする'}</button><button class="action-btn ${isExcluded?'restore':'subtle'}" data-exclude="${name}">${isExcluded?'除外を解除':'狙わない'}</button>${isCaught?`<button class="action-btn edit" data-edit="${name}">状態編集</button>`:''}</div>`}
function encounterCard(e){const rec=recOf(e.name),ex=expOf(e),summary=recordSummary(e.name),isCaught=caught.has(e.name),isExcluded=excluded.has(e.name);return `<article class="encounter-card ${isCaught?'caught':''} ${isExcluded?'excluded':''}"><div class="encounter-top"><div><div class="poke-line"><span class="encounter-name">${e.name}</span>${recBadge(e.name)}</div><div class="encounter-place">${e.location} ・ ${methods[e.method]}</div></div></div><div class="primary-facts"><span class="badge rate">出現 ${e.rate}%</span><span class="badge">${levelText(e)}</span><span class="badge">${periods[e.time]}</span>${e.method.startsWith('head')?'<span class="badge head">ずつき</span>':''}${e.method==='oldrod'?'<span class="badge fish">釣り</span>':''}${isExcluded?'<span class="badge excluded-badge">狙わない</span>':''}</div>${rec?`<div class="why-line">${esc(rec.reason)}</div>`:''}${summary?`<div class="record-mini">${esc(summary)}</div>`:''}<details class="detail-fold"><summary>詳細を見る</summary><div class="detail-grid"><div class="detail-cell"><span>捕獲係数</span><b>${catchRate(e.name)??'—'}</b></div><div class="detail-cell"><span>基礎EXP</span><b>${(meta[e.name]||[])[1]??'—'}</b></div><div class="detail-cell"><span>概算EXP</span><b>${ex??'—'}</b></div></div>${e.note?`<div class="why-line">${esc(e.note)}</div>`:''}</details>${actionButtons(e.name)}</article>`}
function focusCard(e){if(!e)return'<div class="empty">今の条件では未捕獲・未除外の候補がありません。</div>';const rec=recOf(e.name),ex=expOf(e);return `<article class="decision-card"><div class="decision-label">今、最初に見る候補</div><div class="poke-line"><h2>${e.name}</h2>${recBadge(e.name)}</div><div class="decision-sub">${e.location} ・ ${methods[e.method]}</div><div class="fact-row"><span class="fact">出現 ${e.rate}%</span><span class="fact">${levelText(e)}</span><span class="fact">${periods[e.time]}</span>${ex?`<span class="fact">約${ex}EXP</span>`:''}</div><div class="decision-reason">${rec?esc(rec.reason):'未捕獲の候補です。図鑑を進めるなら現在の出現条件で狙えます。'}</div>${actionButtons(e.name,{large:true})}</article>`}

function populate(){
 $('#progressSelect').innerHTML=progress.map(p=>`<option value="${p.id}" ${p.id===currentStage?'selected':''}>${p.name}</option>`).join('');
 const locs=[...new Set(E.map(e=>e.location))];$('#locationFilter').innerHTML='<option value="all">すべての場所</option>'+locs.map(x=>`<option>${x}</option>`).join('');
 $('#methodFilter').innerHTML='<option value="all">すべての方法</option>'+Object.entries(methods).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
 $('#editNature').innerHTML='<option value="">未設定</option>'+natures.map(n=>`<option>${n}</option>`).join('');
}
function availableNow(){const p=getPeriod();return dedupeBest(E.filter(e=>e.stage<=currentStage&&timeOK(e,p)&&!caught.has(e.name)&&!excluded.has(e.name))).sort((a,b)=>targetPriority(b)-targetPriority(a));}
function renderNow(){const avail=availableNow();$('#progressNote').textContent=progress[currentStage].note;$('#nowDecision').innerHTML=focusCard(avail[0]);const next=avail.slice(1,4),other=avail.slice(4);$('#nextTargets').innerHTML=next.length?next.map(encounterCard).join(''):'<div class="empty small">次の候補はありません。</div>';$('#nextCount').textContent=next.length?`${next.length}匹`:'';$('#otherTargets').innerHTML=other.length?other.map(encounterCard).join(''):'<div class="empty small">その他の候補はありません。</div>';$('#otherCount').textContent=`${other.length}匹`;const rare=avail.filter(e=>e.rate<=5).slice(0,3).map(e=>`${e.name} ${e.rate}%`);const strong=avail.filter(e=>(recOf(e.name)?.score||0)>=4).slice(0,3).map(e=>e.name);$('#todayTip').innerHTML=strong.length?`<strong>育成価値が高い候補：</strong>${strong.join(' / ')}${rare.length?`<br><strong>低確率：</strong>${rare.join(' / ')}`:''}`:(rare.length?`<strong>低確率：</strong>${rare.join(' / ')}`:'未捕獲は高出現率のものから回収すると効率的です。');}
function renderDex(){const q=$('#search').value.trim(),loc=$('#locationFilter').value,met=$('#methodFilter').value,tf=$('#timeFilter').value,p=tf==='current'?getPeriod():tf;let arr=E.filter(e=>e.stage<=currentStage);if(q)arr=arr.filter(e=>e.name.includes(q)||e.location.includes(q));if(loc!=='all')arr=arr.filter(e=>e.location===loc);if(met!=='all')arr=arr.filter(e=>e.method===met);if(tf!=='all')arr=arr.filter(e=>timeOK(e,p));if($('#uncaughtOnly').checked)arr=arr.filter(e=>!caught.has(e.name));if($('#hideExcluded').checked)arr=arr.filter(e=>!excluded.has(e.name));arr.sort((a,b)=>a.location.localeCompare(b.location,'ja')||b.rate-a.rate);$('#dexCards').innerHTML=arr.length?arr.map(encounterCard).join(''):'<div class="empty">該当する出現データがありません。</div>';}

function recommendationEntries(){const available=new Set(E.filter(e=>e.stage<=currentStage).map(e=>e.name));return Object.entries(recommendations).filter(([n,r])=>available.has(n)&&r.score>=3).sort((a,b)=>b[1].score-a[1].score||a[0].localeCompare(b[0],'ja'));}
function recommendationCard(name,r){return `<article class="recommend-card ${caught.has(name)?'owned':''}"><div class="recommend-head"><b>${name}</b><span class="rec rec-${r.cls}">${r.label}</span></div><p>${esc(r.reason)}</p><div class="recommend-foot">${caught.has(name)?'✓ 捕獲済み':excluded.has(name)?'— 狙わない':'未捕獲'}</div></article>`}
function renderRecommendations(){const arr=recommendationEntries();$('#recommendList').innerHTML=arr.slice(0,4).map(([n,r])=>recommendationCard(n,r)).join('')||'<div class="empty">候補がありません。</div>';$('#recommendAll').innerHTML=arr.map(([n,r])=>recommendationCard(n,r)).join('')||'<div class="empty">候補がありません。</div>';}
function expEntries(){let arr=E.filter(e=>['grass','oldrod'].includes(e.method)&&e.stage<=currentStage);return dedupeBest(arr).map(e=>({...e,exp:expOf(e)})).filter(e=>e.exp);}
function expMiniCard(label,e,variant=''){if(!e)return'';const g=expGrade(e);return `<article class="mini-decision ${variant}"><div class="mini-label">${label}</div><h3>${e.name} <span class="exp-grade exp-${g.cls}">${g.label}</span></h3><p>${e.location} ・ ${levelText(e)} ・ 出現${e.rate}%<br><strong>約${e.exp} EXP/1匹</strong><br>${g.note}</p></article>`}
function renderTrainingDecision(){const recs=recommendationEntries(),owned=recs.find(([n,r])=>caught.has(n)&&r.score>=4),upgrade=recs.find(([n,r])=>!caught.has(n)&&!excluded.has(n)&&r.score>=4);const parts=[];if(owned){const[n,r]=owned;parts.push(`<article class="mini-decision best"><div class="mini-label">今いる中で育成優先</div><h3>${n} <span class="rec rec-${r.cls}">${r.label}</span></h3><p>${esc(r.reason)}</p></article>`)}if(upgrade){const[n,r]=upgrade;parts.push(`<article class="mini-decision"><div class="mini-label">次に加えるなら</div><h3>${n} <span class="rec rec-${r.cls}">${r.label}</span></h3><p>${esc(r.reason)}</p></article>`)}if(!parts.length&&recs[0]){const[n,r]=recs[0];parts.push(`<article class="mini-decision"><div class="mini-label">育成候補</div><h3>${n} <span class="rec rec-${r.cls}">${r.label}</span></h3><p>${esc(r.reason)}</p></article>`)}$('#trainingDecision').innerHTML=parts.join('');}
function renderExp(){const arr=expEntries();const ranked=[...arr].sort((a,b)=>expInternalScore(b)-expInternalScore(a));const stable=ranked.find(e=>expGrade(e).level>=3)||ranked[0];const high=[...arr].sort((a,b)=>b.exp-a.exp)[0];const caution=[...arr].filter(e=>e.rate<=5).sort((a,b)=>b.exp-a.exp)[0];$('#expHighlights').innerHTML=expMiniCard('安定して稼ぐ',stable,'best')+expMiniCard('1匹のEXP重視',high)+expMiniCard('低出現に注意',caution,'caution');const restrict=$('#expCurrent').checked;let detail=restrict?ranked:dedupeBest(E.filter(e=>['grass','oldrod'].includes(e.method))).map(e=>({...e,exp:expOf(e)})).filter(e=>e.exp).sort((a,b)=>expInternalScore(b)-expInternalScore(a));$('#expRank').innerHTML=detail.slice(0,20).map((e,i)=>{const g=expGrade(e);return `<div class="rank"><div class="rankno">${i+1}</div><div class="rankbody"><div class="ranktitle">${e.name} ${levelText(e)} <span class="exp-grade exp-${g.cls}">${g.label}</span></div><div class="ranksub">${e.location} ・ 出現${e.rate}% ・ ${g.note}</div></div><div class="rankexp"><b>約${e.exp}</b><span>EXP/1匹</span></div></div>`}).join('');$('#levelAdvice').innerHTML=currentStage>=5?'<strong>結論：</strong>35番道路のスリープのような「高めのEXP＋十分な出現率」を優先。オドシシのような低出現枠は、見つかったら倒す程度が効率的です。':currentStage>=4?'<strong>結論：</strong>34番道路のスリープが安定。野生だけに偏らず、未撃破トレーナーを先に使うのが効率的です。':'<strong>結論：</strong>序盤はトレーナー戦優先。野生は不足分だけ補います。';renderRecommendations();renderTrainingDecision();}

function manageCard(name){const r=recordFor(name),rec=recOf(name);return `<article class="manage-card"><div class="manage-main"><div class="manage-head"><div class="poke-line"><span class="manage-name">${name}</span>${recBadge(name)}</div><button class="action-btn edit" data-edit="${name}">編集</button></div><div class="state-line">${r.currentState?`<span class="state-chip current">現在：${esc(r.currentState)}</span>`:'<span class="state-chip">現在：未設定</span>'}${r.plan?`<span class="state-chip plan">予定：${esc(r.plan)}</span>`:'<span class="state-chip">予定：未設定</span>'}${r.level?`<span class="state-chip">Lv${esc(r.level)}</span>`:''}</div>${r.nickname||r.nature||r.ability||r.item?`<div class="manage-detail">${r.nickname?`「${esc(r.nickname)}」　`:''}${r.nature?`性格 ${esc(r.nature)}　`:''}${r.ability?`特性 ${esc(r.ability)}　`:''}${r.item?`持ち物 ${esc(r.item)}`:''}</div>`:''}${r.memo?`<div class="manage-memo">${esc(r.memo)}</div>`:''}</div></article>`}
function renderManage(){const q=$('#manageSearch').value.trim(),current=$('#manageCurrent').value,plan=$('#managePlan').value;let names=[...caught].filter(n=>E.some(e=>e.name===n));if(q)names=names.filter(n=>n.includes(q)||(recordFor(n).nickname||'').includes(q));if(current!=='all')names=names.filter(n=>(recordFor(n).currentState||'未設定')===current);if(plan!=='all')names=names.filter(n=>(recordFor(n).plan||'未設定')===plan);names.sort((a,b)=>(recordFor(a).currentState==='手持ち'?0:1)-(recordFor(b).currentState==='手持ち'?0:1)||(recOf(b)?.score||0)-(recOf(a)?.score||0)||a.localeCompare(b,'ja'));$('#manageCards').innerHTML=names.length?names.map(manageCard).join(''):'<div class="empty">条件に合う捕獲済みポケモンがありません。</div>';const ex=[...excluded].sort((a,b)=>a.localeCompare(b,'ja'));$('#excludedList').innerHTML=ex.length?ex.map(n=>`<div class="excluded-row"><span>${n}</span><button class="action-btn restore" data-exclude="${n}">解除</button></div>`).join(''):'<div class="empty small">狙わない設定はありません。</div>';const all=[...caught].map(recordFor);$('#partyCount').textContent=all.filter(r=>r.currentState==='手持ち').length;$('#boxCount').textContent=all.filter(r=>r.currentState==='ボックス').length;$('#plannedCount').textContent=all.filter(r=>r.plan&&r.plan!=='特になし').length;}
function renderStats(){const visibleSpecies=new Set(E.filter(e=>e.stage<=currentStage).map(e=>e.name)),c=[...caught].filter(n=>visibleSpecies.has(n)).length,total=visibleSpecies.size;$('#caughtCount').textContent=c;$('#uncaughtCount').textContent=Math.max(0,total-c);$('#excludedCount').textContent=excluded.size;$('#caughtProgressText').textContent=`${c} / ${total}`;$('#excludedText').textContent=excluded.size;$('#caughtBar').style.width=`${total?Math.round(c/total*100):0}%`;}
function renderAll(){renderNow();renderDex();renderExp();renderManage();renderStats();}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});const p=getPeriod();$('#period').textContent=p==='morning'?'朝':p==='day'?'昼':'夜';$('#periodHero').textContent=p==='morning'?'朝':p==='day'?'昼':'夜';}
function openEditor(name){const r=recordFor(name);$('#dialogName').textContent=name;$('#editSpecies').value=name;$('#editLevel').value=r.level||'';$('#editCurrent').value=r.currentState||'';$('#editPlan').value=r.plan||'';$('#editNickname').value=r.nickname||'';$('#editNature').value=r.nature||'';$('#editAbility').value=r.ability||'';$('#editItem').value=r.item||'';$('#editMemo').value=r.memo||'';$('#pokeDialog').showModal();}

populate();clock();setInterval(clock,30000);renderAll();
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
$('#progressSelect').onchange=e=>{currentStage=Number(e.target.value);save();renderAll();notify('進行度を更新しました')};
['search','locationFilter','methodFilter','timeFilter','uncaughtOnly','hideExcluded'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderDex));
['manageSearch','manageCurrent','managePlan'].forEach(id=>$('#'+id).addEventListener(id==='manageSearch'?'input':'change',renderManage));
$('#expCurrent').onchange=renderExp;
document.addEventListener('click',e=>{const catchBtn=e.target.closest('[data-catch]');if(catchBtn){const n=catchBtn.dataset.catch;if(caught.has(n)){caught.delete(n);notify(`${n}の捕獲チェックを解除`)}else{caught.add(n);excluded.delete(n);notify(`${n}を捕獲済みにしました`)}save();renderAll();return;}const excludeBtn=e.target.closest('[data-exclude]');if(excludeBtn){const n=excludeBtn.dataset.exclude;if(excluded.has(n)){excluded.delete(n);notify(`${n}を候補へ戻しました`)}else{excluded.add(n);notify(`${n}を「狙わない」にしました`)}save();renderAll();return;}const editBtn=e.target.closest('[data-edit]');if(editBtn){openEditor(editBtn.dataset.edit);return;}});
$('#pokeForm').addEventListener('submit',e=>{e.preventDefault();const n=$('#editSpecies').value;records[n]={nickname:$('#editNickname').value.trim(),level:$('#editLevel').value,currentState:$('#editCurrent').value,plan:$('#editPlan').value,nature:$('#editNature').value,ability:$('#editAbility').value.trim(),item:$('#editItem').value.trim(),memo:$('#editMemo').value.trim()};save();$('#pokeDialog').close();renderAll();notify(`${n}の状態を保存しました`)});
$('#closeDialog').onclick=()=>$('#pokeDialog').close();
$('#clearRecord').onclick=()=>{const n=$('#editSpecies').value;if(confirm(`${n}の状態記録を消しますか？`)){delete records[n];save();$('#pokeDialog').close();renderAll();notify('状態記録を消しました')}};
$('#pokeDialog').addEventListener('click',e=>{if(e.target===$('#pokeDialog'))$('#pokeDialog').close()});
$('#resetBtn').onclick=()=>{if(confirm('捕獲チェックをすべてリセットしますか？\n状態メモと「狙わない」設定は残ります。')){caught.clear();save();renderAll();notify('捕獲チェックをリセットしました')}};
$('#exportBtn').onclick=()=>{const lines=['【ソウルシルバー 図鑑・育成ナビ】',''];[...caught].sort((a,b)=>a.localeCompare(b,'ja')).forEach(n=>{const r=recordFor(n);let s=`☑ ${n}`;if(r.level)s+=` Lv${r.level}`;if(r.currentState)s+=` / 現在:${r.currentState}`;if(r.plan)s+=` / 予定:${r.plan}`;if(r.nature)s+=` / ${r.nature}`;if(r.memo)s+=` / ${r.memo}`;lines.push(s)});if(excluded.size){lines.push('','【狙わない】',...[...excluded].sort((a,b)=>a.localeCompare(b,'ja')).map(n=>'－ '+n));}const text=lines.join('\n');if(navigator.share){navigator.share({title:'ソウルシルバー 捕獲・育成データ',text}).catch(()=>{})}else{navigator.clipboard?.writeText(text);notify('一覧をコピーしました')}};
